### ISSUE TITLE
Continual Status MQTT Commands

### ISSUE THREAD

**Issue by benmprojects** [marthoc/GarHAge#26]
Hi,

I have just hooked up my reed switch and it is reporting the state correctly but I receive continual garage/door/1/status reports every 2 seconds. Looking at the code this should not happen as the CurrentState is the same as PreviousState.

Any ideas?

Thanks Ben

**Comment by marthoc** [comment]
Can you try the dev branch? There have been some updates which may address. Otherwise you may need to add a pull-up resistor on the input pin to hold it high, it sounds like it could be floating. Not all esp8266 hardware packages are made equal unfortunately and it could be that the pull-ups in whatever version you have just aren’t doing it.

**Comment by benmprojects** [comment]
Hi Mark, pull up resistor worked. Thanks for your reply.
